### ISSUE TITLE
This project cannot be built

### ISSUE THREAD

**Issue by jtal** [pac4j/play-pac4j-java-demo#10]
build.sbt refers to a versions of components (e.g. pac4j-cas) which is no longer exist in the sonatype repository (1.7.0-SNAPSHOT).

If you change them to use 1.7.1-SNAPSHOT you get the error that pac4j-core 1.7.0-SNAPSHOT doesnt exist even though it is not explicitly included. It must be play-pac4j_java requiring core 1.7.0 as a dependency?

I got around this problem in my app by including in this order:

  "org.pac4j" % "pac4j-core" % "1.7.1-SNAPSHOT",
  "org.pac4j" % "play-pac4j_java" % "1.4.0-SNAPSHOT",
  "org.pac4j" % "pac4j-cas" % "1.7.1-SNAPSHOT"

I hope this will work but I have a question. What does it mean when a version disappears from the repo? Was there a security problem with it? Do you only remove SNAPSHOTs or will normal releases disappear in the future? I'm just worried one day the version my production app relies on will disappear.

I have been using your libraries for a few years now. It is simple in design and works really well. Thank you.

**Comment by leleuj** [comment]
Indeed, I released pac4j v1.7.0 and the snapshot has been removed: no security issue, a regular way to say that it's time to upgrade. You should use version 1.7.0.
There are many related libraries (like play-pac4j, j2e-pac4j, spring-security-pac4j, buji-pac4j...) and I'm currently upgrading them with this new release of pac4j...

**No worries**

**Comment by jtal** [comment]
oooh, I understand. I only have to go to sonatype for snapshots. I get it now. 

I'm still using play-pac4j_java 1.1.x in a production play 2.1.x app by the way :)

Thanks again
