### ISSUE TITLE
demo appears to depend on unavailable code

### ISSUE THREAD

**Issue by paulopinheiro1234** [pac4j/play-pac4j-java-demo#110]
The code does not run with the use of the bin/activator provided with the project or with stb run.

Typesafe repository: unable to get resource for net/virtual-void#sbt-dependency-graph;0.9.2: res=http://repo.typesafe.com/typesafe/releases/net/virtual-void/sbt-dependency-graph_2.12_1.0/0.9.2/sbt-dependency-graph-0.9.2.pom: java.net.ConnectException: Failed to connect to repo.typesafe.com/34.193.5.230:80

**Comment by leleuj** [comment]
I must have it already downloaded as I don't have the issue. I commented out the dependency. Can you try again? Thanks

**Comment by InBrewJ** [comment]
For anyone else stuck on this, change the first line of `project/plugins.sbt` from this:

```
resolvers += "Typesafe repository" at "http://repo.typesafe.com/typesafe/releases/"
```
to this:
```
resolvers += "Typesafe repository" at "https://repo.typesafe.com/typesafe/ivy-releases/"
```

If you go to `http://repo.typesafe.com/` (explicitly `http`) in a browser you're redirected to `https://repo.typesafe.com/` and, from what I can gather, it's basically telling you to change the "Typesafe repository" resolver. 

I'm no Scala or sbt expert but the after the change the demo builds + runs just fine :ok_hand:
