### ISSUE TITLE
integration with openAM

### ISSUE THREAD

**Issue by hboumedane** [pac4j/play-pac4j-java-demo#17]
Hello,
I'm trying to integrate this app with openAM but i could'nt find any doc on how to do that ?
is there any doc that show how to integrate this app with openAM intstead of openidp?

**Comment by leleuj** [comment]
What protocol does OpenAM support?

**Comment by hboumedane** [comment]
SAML 2

**Comment by leleuj** [comment]
OK. There is no specific documentation for OpenAM, we have

**Comment by leleuj** [comment]
This might help as well: https://github.com/pac4j/pac4j/wiki/Code-samples, "SAML" part...

**Comment by hboumedane** [comment]
thanks for the help, i will see those examples and try to get this app work against openAM.

**Comment by leleuj** [comment]
Be careful between `pac4j` 1.7.0 and 1.7.1: the way to configure the SAML support has changed. Follow this demo for v1.7.0 or this one: https://github.com/pac4j/j2e-pac4j-demo for v1.7.1

**Comment by hboumedane** [comment]
ok.
