### ISSUE TITLE
Default users (jle, pwd)

### ISSUE THREAD

**Issue by nmatkheev** [pac4j/play-pac4j-java-demo#38]
Hi guys!

Could you explain where default users are defined?
Tried to find with debug (set breakpoint to callback function), and searched occurrences in path ('pwd') - nothing revealed.

**Comment by leleuj** [comment]
The `SimpleTestUsernamePasswordAuthenticator` (https://github.com/pac4j/play-pac4j-java-demo/blob/master/app/modules/SecurityModule.java#L63) defines how to validate credentials: in that case, login = pwd is ok.

**Comment by nmatkheev** [comment]
Thanx for reply. I got it.
Now I'm trying to modify this demo to use SQL authenticator.

I know about pac4j-sql, but I don't realize how to use it properly. 
Could you help me?

**Comment by leleuj** [comment]
It should make things clearer: http://www.pac4j.org/1.9.x/docs/authenticators/sql.html

**Comment by nmatkheev** [comment]
I'd read this page previously. Still not obvious for beginner like me.
Please correct my thoughts if wrong:

1) This code I should embed to SecurityModule:
```
DataSource dataSource = JdbcConnectionPool.create("jdbc:h2:mem:test", dbuser, dbpwd);
DbAuthenticator authenticator = new DbAuthenticator(dataSource);
```
I already have db integration via Play and Ebean. Can I use this one, or should explicitly put connection in datasource parameters? 

2) Basically, there's no need in my own versions of CustomAuthorizer and DemoHttpAdapter, right?

**Comment by leleuj** [comment]
1. You need to build the `DbAuthenticator` from a `DataSource`, so you must obtain one from `Ebean`: I don't know how, though.

2. Indeed, the `CustomAuthorizer` is for specific authorizations checks and the `DemoHttpAdapter` is for custom 401 / 403 error pages.
