### ISSUE TITLE
Role establishing

### ISSUE THREAD

**Issue by nmatkheev** [pac4j/play-pac4j-java-demo#39]
Hello again :)

I read this topic: (http://www.pac4j.org/1.9.x/docs/clients.html#compute-roles-and-permissions)

1. Should I put AuthorizationGenerator into my SecurityModule?
2. Where to store information about roles? Into approriate table's column? What else have I got to do?
3. About attributes - as I understood, it's enough to put this snippet in SecurityModule:
`authenticator.setAttributes("firstname, middlename, lastname, phone, email");`
   But visible become only firstname and phone: 
  ````
   private List<CommonProfile> getProfiles() {
        final PlayWebContext context = new PlayWebContext(ctx(), playSessionStore);
        final ProfileManager<CommonProfile> profileManager = new ProfileManager(context);
        return profileManager.getAll(true);
    }
   ````
   Should I define my own profile class?

It would be a great relief for newbie if you provide some snippets/examples of working with roles

**Comment by leleuj** [comment]
Please use the mailing list for questions: https://groups.google.com/forum/?fromgroups#!forum/pac4j-users

1. yes, and attach it to a client or to all clients
2. wherever you want. If loaded by the database as attributes, the AuthorizationGenerator will need to turn them into roles / permissions
3. all attributes should be available, either with a specific getter (`getEmail` for example) or via the generic one (`getAttribute(name)`).
