### ISSUE TITLE
Do you provide test spec and example for Scala?

### ISSUE THREAD

**Issue by jeffwji** [pac4j/play-pac4j-java-demo#56]
I'm using pac4j with Scala environment, and have difficulty when I'm writing a test case using PlaySpec to test a secured url, which's controller requires `SecurityComponents` instead of default Play `ControllerComponments`, the interface definition as bellow:

    class AuthController @Inject() (
        val controllerComponents: SecurityComponents,
        val appConf: Configuration
    ) extends Security[CommonProfile]

So it is no way to use the default `stubControllerComponents()` to grab a `SecurityComponents` object

    val controller = new AuthController(stubControllerComponents(), app.configuration)

This code reports type mismatch, and I recognized `SecurityComponents` is provided by pac4j, not from Play. Not sure is there any way I can adopt it in the test case by auto injection?

**Comment by leleuj** [comment]
Please use the mailing list for questions: https://groups.google.com/forum/?fromgroups#!forum/pac4j-users
